dbt_enterprise_models:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      user: "{{ env_var('DB_TRANSFORM_USER') }}"
      password: "{{ env_var('DB_TRANSFORM_PASSWORD') }}"
      database: "{{ env_var('DB_TRANSFORM_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: test

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      user: "{{ env_var('DB_TRANSFORM_USER') }}"
      password: "{{ env_var('DB_TRANSFORM_PASSWORD') }}"
      database: "{{ env_var('DB_TRANSFORM_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: transform

    # dev:
    #   type: redshift
    #   host: "{{ env_var('REDSHIFT_HOST') }}"
    #   user: "{{ env_var('DB_TRANSFORM_USER') }}"
    #   password: "{{ env_var('DB_TRANSFORM_PASSWORD') }}"
    #   dbname: "{{ env_var('DB_TRANSFORM_DATABASE') }}"
    #   port: 5439
    #   schema: test
    #   threads: 4
    #   sslmode: prefer
    #   keepalives_idle: 240
    #   connect_timeout: 10

    # prod:
    #   type: redshift
    #   host: "{{ env_var('REDSHIFT_HOST') }}"
    #   user: "{{ env_var('DB_TRANSFORM_USER') }}"
    #   password: "{{ env_var('DB_TRANSFORM_PASSWORD') }}"
    #   dbname: "{{ env_var('DB_TRANSFORM_DATABASE') }}"
    #   port: 5439
    #   schema: transform
    #   threads: 4
    #   sslmode: prefer
    #   keepalives_idle: 240
    #   connect_timeout: 10