# Copy this file to ~/profiles.yaml and fill in your credentials
# Do NOT commit the real profiles.yml to git!

dbt_enterprise_models:
  target: dev
  outputs:
    dev_snowflake:
      type: snowflake # Change to 'databricks' if using Databricks
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" # e.g., xy12345.us-east-1
      user: "{{ env_var('SNOWFLAKE_USER') }}" # e.g., DBT_USER
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'ANALYTICS') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: dev_dn # Your dev schema — change to your name/initials
      threads: 8
      client_session_keep_alive: true

    prod_snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_PROD_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PROD_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_PROD_ROLE', 'PROD_ROLE') }}"
      database: ANALYTICS
      warehouse: PROD_WH
      schema: analytics
      threads: 16
      client_session_keep_alive: true

    # dev_databricks:
    #   type: databricks
    #   host: "{{ env_var('DATABRICKS_HOST') }}"  # e.g., adb-1234567890.1.azuredatabricks.net
    #   http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"  # /sql/1.0/warehouses/abc123
    #   token: "{{ env_var('DATABRICKS_TOKEN') }}"
    #   catalog: "{{ env_var('DATABRICKS_CATALOG', 'main') }}"
    #   schema: dev_donovan
    #   threads: 8

    # prod_databricks:
    #   type: databricks
    #   host: "{{ env_var('DATABRICKS_HOST') }}"
    #   http_path: "{{ env_var('DATABRICKS_PROD_HTTP_PATH') }}"
    #   token: "{{ env_var('DATABRICKS_PROD_TOKEN') }}"
    #   catalog: main
    #   schema: analytics
    #   threads: 16