version: 2

sources:
  - name: extract
    schema: extract
    tables:
      - name: exchange_rates
      - name: stripe_charges
      - name: stripe_payments
      - name: stripe_refunds
      - name: google_ads_campaigns
      - name: google_ads_ad_groups
      - name: google_ads_ads
      - name: google_ads_clicks
      - name: facebook_ads_campaigns
      - name: facebook_ads_ad_sets
      - name: facebook_ads_ads
      - name: prod_customers
      - name: prod_orders
      - name: prod_order_items
      - name: prod_products